services:
  db:
    image: postgres:17-alpine
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database

  api:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/database
    command: /bin/bash -c "
      until pg_isready -h db -p 5432 -U postgres; do
        sleep 1;
      done &&
      alembic upgrade head &&
      python seed_data.py &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    ports:
      - 8000:8000
    volumes:
      - .:/app

volumes:
  postgres_data: