version: "3.8"

services:
  test_db:
    image: postgres:17-alpine
    container_name: test_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

volumes:
  test_postgres_data: