"""Add models

Revision ID: 806ce371f995
Revises: 
Create Date: 2025-06-07 14:28:52.587256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '806ce371f995'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_dataset_entities',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('test_listings',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('scan_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('dataset_entity_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('image_hashes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_test_listings_listing_id'), 'test_listings', ['listing_id'], unique=False)
    op.create_table('test_properties',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.CheckConstraint("type IN ('string', 'boolean')", name='check_property_type'),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_table('test_property_values_bool',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['test_listings.listing_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['test_properties.property_id'], ),
    sa.PrimaryKeyConstraint('listing_id', 'property_id')
    )
    op.create_table('test_property_values_str',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['test_listings.listing_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['test_properties.property_id'], ),
    sa.PrimaryKeyConstraint('listing_id', 'property_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_property_values_str')
    op.drop_table('test_property_values_bool')
    op.drop_table('test_properties')
    op.drop_index(op.f('ix_test_listings_listing_id'), table_name='test_listings')
    op.drop_table('test_listings')
    op.drop_table('test_dataset_entities')
    # ### end Alembic commands ###
